-- Criação de schema mínimo para a agenda (Oracle 12c+)
CREATE TABLE PACIENTES (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR2(120) NOT NULL,
  EMAIL VARCHAR2(200) NOT NULL
);

CREATE TABLE MEDICOS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR2(120) NOT NULL,
  CRM  VARCHAR2(40)  NOT NULL
);

CREATE TABLE CONSULTAS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PACIENTE_ID NUMBER NOT NULL REFERENCES PACIENTES(ID),
  MEDICO_ID   NUMBER NOT NULL REFERENCES MEDICOS(ID),
  INICIO TIMESTAMP NOT NULL,
  FIM    TIMESTAMP NOT NULL
);

-- Dados de exemplo
INSERT INTO PACIENTES (NOME, EMAIL) VALUES ('Alice', 'alice@exemplo.com');
INSERT INTO PACIENTES (NOME, EMAIL) VALUES ('Bruno', 'bruno@exemplo.com');

INSERT INTO MEDICOS (NOME, CRM) VALUES ('Dra. Carla', 'CRM1234');
INSERT INTO MEDICOS (NOME, CRM) VALUES ('Dr. Diego', 'CRM5678');

COMMIT;
