
-- Tabelas para Oracle
CREATE TABLE pacientes (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(120) NOT NULL,
  email VARCHAR2(120) NOT NULL UNIQUE
);

CREATE TABLE medicos (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(120) NOT NULL,
  crm  VARCHAR2(20) NOT NULL UNIQUE
);

CREATE TABLE consultas (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id NUMBER NOT NULL REFERENCES pacientes(id),
  medico_id   NUMBER NOT NULL REFERENCES medicos(id),
  inicio      TIMESTAMP NOT NULL,
  fim         TIMESTAMP NOT NULL,
  CONSTRAINT chk_intervalo CHECK (fim > inicio)
);

CREATE INDEX idx_consultas_medico_tempo ON consultas (medico_id, inicio, fim);

COMMIT;
